### ISSUE TITLE
Add a customized layer and compilation failed!

### ISSUE THREAD

**Issue by hadoop2xu** [Tencent/TurboTransformers#111]
编译turbo,运行benchmark报错
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/turbo_transformers/layers/modeling_bert.py", line 16, in <module>
    import turbo_transformers.turbo_transformers_cxxd as cxx
ModuleNotFoundError: No module named 'turbo_transformers.turbo_transformers_cxxd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gpu_benchmark.py", line 114, in <module>
    main()
  File "gpu_benchmark.py", line 104, in main
    benchmark_turbo_transformers(**kwargs)
  File "gpu_benchmark.py", line 38, in benchmark_turbo_transformers
    import turbo_transformers
  File "/usr/local/lib/python3.6/dist-packages/turbo_transformers/__init__.py", line 14, in <module>
    from .layers import *
  File "/usr/local/lib/python3.6/dist-packages/turbo_transformers/layers/__init__.py", line 14, in <module>
    from .modeling_bert import BertEmbeddings, BertIntermediate, BertOutput, BertAttention, BertLayer, SequencePool, \
  File "/usr/local/lib/python3.6/dist-packages/turbo_transformers/layers/modeling_bert.py", line 18, in <module>
    import turbo_transformers.turbo_transformers_cxx as cxx
ImportError: /usr/local/lib/python3.6/dist-packages/turbo_transformers/turbo_transformers_cxx.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK18turbo_transformers6layers15DEEPFMEmbeddingclERKNS_4core6TensorEPS3_
请问大佬，可能是什么原因呢？

**Comment by hadoop2xu** [comment]
代码中添加了一个layer类，然后编译的

**Comment by feifeibear** [comment]
你有没有follow这个https://github.com/Tencent/TurboTransformers/blob/master/turbo_transformers/layers/README.md

**Comment by hadoop2xu** [comment]
> 你有没有follow这个https://github.com/Tencent/TurboTransformers/blob/master/turbo_transformers/layers/README.md

没有提供python API，只做了1、4两步

**Comment by hadoop2xu** [comment]
> 你有没有follow这个https://github.com/Tencent/TurboTransformers/blob/master/turbo_transformers/layers/README.md
谢谢，我的turbo版本有点老了 ，需要更新一下

**Comment by feifeibear** [comment]
我们更新会很频繁，你可以star一下我们的项目，保证使用最新的版本。

**Comment by hadoop2xu** [comment]
> 我们更新会很频繁，你可以star一下我们的项目，保证使用最新的版本。

👌
