### ISSUE TITLE
bug: failed to run run_cpu_fixed_benchmark.sh

### ISSUE THREAD

**Issue by flans39** [Tencent/TurboTransformers#145]
./run_cpu_fixed_benchmark.sh
```
using CPU
Traceback (most recent call last):
  File "benchmark.py", line 72, in <module>
    main()
  File "benchmark.py", line 60, in main
    benchmark_torch(**kwargs)
  File "/root/TurboTransformers/benchmark/torch_benchmark_helper.py", line 60, in benchmark_torch
    batch_size, seq_len, "torch")
  File "/root/TurboTransformers/benchmark/benchmark_helper.py", line 55, in run_model
    "thread_num": thread_num,
NameError: name 'thread_num' is not defined
```

https://github.com/Tencent/TurboTransformers/blob/faf28dc29a4aed87a3f5bc8489dc94ce76cbf62e/benchmark/benchmark_helper.py#L23

https://github.com/Tencent/TurboTransformers/blob/faf28dc29a4aed87a3f5bc8489dc94ce76cbf62e/benchmark/benchmark_helper.py#L55

**Comment by feifeibear** [comment]
fixed in my next PR on develop
