### ISSUE TITLE
unitest fail

### ISSUE THREAD

**Issue by lsy641** [Tencent/TurboTransformers#47]
Test project /tmp/build
      Start  1: tt_core_test
 1/12 Test  #1: tt_core_test .....................   Passed    0.01 sec
      Start  2: tt_kernels_test
 2/12 Test  #2: tt_kernels_test ..................   Passed    0.09 sec
      Start  3: bert_attention_test
 3/12 Test  #3: bert_attention_test ..............***Failed    0.39 sec
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2020-05-16 14:14:00.527 (   0.000s) [main thread     ]             loguru.cpp:610   INFO| arguments: turbo_transformers_cxx
2020-05-16 14:14:00.527 (   0.000s) [main thread     ]             loguru.cpp:613   INFO| Current dir: /tmp/build/turbo_transformers/python
2020-05-16 14:14:00.527 (   0.000s) [main thread     ]             loguru.cpp:615   INFO| stderr verbosity: 0
2020-05-16 14:14:00.527 (   0.000s) [main thread     ]             loguru.cpp:616   INFO| -----------------------------------
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/bert_attention_test.py", line 27, in <module>
    import turbo_transformers
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/__init__.py", line 14, in <module>
    from .layers import *
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/__init__.py", line 14, in <module>
    from .modeling_bert import BertEmbeddings, BertIntermediate, BertOutput, BertAttention, BertLayer, SequencePool, \
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/modeling_bert.py", line 20, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
2020-05-16 14:14:00.800 (   0.272s) [main thread     ]             loguru.cpp:489   INFO| atexit

      Start  4: bert_embedding_test
 4/12 Test  #4: bert_embedding_test ..............***Failed    0.35 sec
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2020-05-16 14:14:00.890 (   0.000s) [main thread     ]             loguru.cpp:610   INFO| arguments: turbo_transformers_cxx
2020-05-16 14:14:00.890 (   0.000s) [main thread     ]             loguru.cpp:613   INFO| Current dir: /tmp/build/turbo_transformers/python
2020-05-16 14:14:00.890 (   0.000s) [main thread     ]             loguru.cpp:615   INFO| stderr verbosity: 0
2020-05-16 14:14:00.890 (   0.000s) [main thread     ]             loguru.cpp:616   INFO| -----------------------------------
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/bert_embedding_test.py", line 27, in <module>
    import turbo_transformers
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/__init__.py", line 14, in <module>
    from .layers import *
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/__init__.py", line 14, in <module>
    from .modeling_bert import BertEmbeddings, BertIntermediate, BertOutput, BertAttention, BertLayer, SequencePool, \
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/modeling_bert.py", line 20, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
2020-05-16 14:14:01.152 (   0.262s) [main thread     ]             loguru.cpp:489   INFO| atexit

      Start  5: bert_encoder_test
 5/12 Test  #5: bert_encoder_test ................***Failed    0.40 sec
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2020-05-16 14:14:01.251 (   0.000s) [main thread     ]             loguru.cpp:610   INFO| arguments: turbo_transformers_cxx
2020-05-16 14:14:01.251 (   0.000s) [main thread     ]             loguru.cpp:613   INFO| Current dir: /tmp/build/turbo_transformers/python
2020-05-16 14:14:01.251 (   0.000s) [main thread     ]             loguru.cpp:615   INFO| stderr verbosity: 0
2020-05-16 14:14:01.251 (   0.000s) [main thread     ]             loguru.cpp:616   INFO| -----------------------------------
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/bert_encoder_test.py", line 27, in <module>
    import turbo_transformers
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/__init__.py", line 14, in <module>
    from .layers import *
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/__init__.py", line 14, in <module>
    from .modeling_bert import BertEmbeddings, BertIntermediate, BertOutput, BertAttention, BertLayer, SequencePool, \
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/modeling_bert.py", line 20, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
2020-05-16 14:14:01.547 (   0.296s) [main thread     ]             loguru.cpp:489   INFO| atexit

      Start  6: bert_intermediate_test
 6/12 Test  #6: bert_intermediate_test ...........***Failed    0.30 sec
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/bert_intermediate_test.py", line 30, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

      Start  7: bert_layer_test
 7/12 Test  #7: bert_layer_test ..................***Failed    0.41 sec
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2020-05-16 14:14:01.948 (   0.000s) [main thread     ]             loguru.cpp:610   INFO| arguments: turbo_transformers_cxx
2020-05-16 14:14:01.949 (   0.000s) [main thread     ]             loguru.cpp:613   INFO| Current dir: /tmp/build/turbo_transformers/python
2020-05-16 14:14:01.949 (   0.000s) [main thread     ]             loguru.cpp:615   INFO| stderr verbosity: 0
2020-05-16 14:14:01.949 (   0.000s) [main thread     ]             loguru.cpp:616   INFO| -----------------------------------
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/bert_layer_test.py", line 27, in <module>
    import turbo_transformers
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/__init__.py", line 14, in <module>
    from .layers import *
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/__init__.py", line 14, in <module>
    from .modeling_bert import BertEmbeddings, BertIntermediate, BertOutput, BertAttention, BertLayer, SequencePool, \
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/modeling_bert.py", line 20, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
2020-05-16 14:14:02.254 (   0.305s) [main thread     ]             loguru.cpp:489   INFO| atexit

      Start  8: bert_model_test
 8/12 Test  #8: bert_model_test ..................***Failed    0.30 sec
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/bert_model_test.py", line 28, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

      Start  9: bert_output_test
 9/12 Test  #9: bert_output_test .................***Failed    0.33 sec
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2020-05-16 14:14:02.656 (   0.000s) [main thread     ]             loguru.cpp:610   INFO| arguments: turbo_transformers_cxx
2020-05-16 14:14:02.656 (   0.000s) [main thread     ]             loguru.cpp:613   INFO| Current dir: /tmp/build/turbo_transformers/python
2020-05-16 14:14:02.656 (   0.000s) [main thread     ]             loguru.cpp:615   INFO| stderr verbosity: 0
2020-05-16 14:14:02.656 (   0.000s) [main thread     ]             loguru.cpp:616   INFO| -----------------------------------
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/bert_output_test.py", line 27, in <module>
    import turbo_transformers
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/__init__.py", line 14, in <module>
    from .layers import *
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/__init__.py", line 14, in <module>
    from .modeling_bert import BertEmbeddings, BertIntermediate, BertOutput, BertAttention, BertLayer, SequencePool, \
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/modeling_bert.py", line 20, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
2020-05-16 14:14:02.887 (   0.230s) [main thread     ]             loguru.cpp:489   INFO| atexit

      Start 10: bert_pooler_test
10/12 Test #10: bert_pooler_test .................***Failed    0.26 sec
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/bert_pooler_test.py", line 30, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

      Start 11: sequence_pool_test
11/12 Test #11: sequence_pool_test ...............***Failed    0.30 sec
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2020-05-16 14:14:03.253 (   0.000s) [main thread     ]             loguru.cpp:610   INFO| arguments: turbo_transformers_cxx
2020-05-16 14:14:03.253 (   0.000s) [main thread     ]             loguru.cpp:613   INFO| Current dir: /tmp/build/turbo_transformers/python
2020-05-16 14:14:03.253 (   0.000s) [main thread     ]             loguru.cpp:615   INFO| stderr verbosity: 0
2020-05-16 14:14:03.253 (   0.000s) [main thread     ]             loguru.cpp:616   INFO| -----------------------------------
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/sequence_pool_test.py", line 15, in <module>
    import turbo_transformers
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/__init__.py", line 14, in <module>
    from .layers import *
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/__init__.py", line 14, in <module>
    from .modeling_bert import BertEmbeddings, BertIntermediate, BertOutput, BertAttention, BertLayer, SequencePool, \
  File "/tmp/build/turbo_transformers/python/pypackage/turbo_transformers/layers/modeling_bert.py", line 20, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import
2020-05-16 14:14:03.452 (   0.198s) [main thread     ]             loguru.cpp:489   INFO| atexit

      Start 12: tensor_conversion_test
12/12 Test #12: tensor_conversion_test ...........***Failed    0.28 sec
Traceback (most recent call last):
  File "/home/liusiyang/TurboTransformers/turbo_transformers/python/tests/tensor_conversion_test.py", line 14, in <module>
    import torch
  File "/home/liusiyang/anaconda3/envs/python3.6/lib/python3.6/site-packages/torch/__init__.py", line 81, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

17% tests passed, 10 tests failed out of 12

Total Test time (real) =   3.43 sec

The following tests FAILED:
	  3 - bert_attention_test (Failed)
	  4 - bert_embedding_test (Failed)
	  5 - bert_encoder_test (Failed)
	  6 - bert_intermediate_test (Failed)
	  7 - bert_layer_test (Failed)
	  8 - bert_model_test (Failed)
	  9 - bert_output_test (Failed)
	 10 - bert_pooler_test (Failed)
	 11 - sequence_pool_test (Failed)
	 12 - tensor_conversion_test (Failed)
Errors while running CTest

**Comment by feifeibear** [comment]
I guess you did not install turbo in docker. Your torch may not be installed correctly.

**Comment by lsy641** [comment]
yes
