### ISSUE TITLE
gpu benchmark对onnx-runtime的版本支持

### ISSUE THREAD

**Issue by smartcat2010** [Tencent/TurboTransformers#76]
您好！我按照run_gpu_benchmark.sh里注释的，用"pip install onnxruntime-gpu"安装了onnx，添加了"onnxruntime"，运行时遇到了和[该issue](https://github.com/Tencent/TurboTransformers/issues/60)同样的问题，libcublas.so.10无法加载；该issue的解答是让安装老版本1.1.0的onnx；请问，[官方首页](https://github.com/Tencent/TurboTransformers)里的benchmark结果，是和哪个版本的onnx比较的呢？怎样才能跑起来最新版本的onnx作为benchmark对照组呢？

另外，我安装1.1.0的老版本onnx，跑gpu benchmark时也报错：

> Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Warning: ATen was a removed experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.
Traceback (most recent call last):
  File "gpu_benchmark.py", line 114, in <module>
    main()
  File "gpu_benchmark.py", line 108, in main
    benchmark_helper.onnxruntime_benchmark_creator('GPU')(**kwargs)
  File "/workspace/benchmark/benchmark_helper.py", line 114, in _impl_
    graph_optimization_level=onnxruntime.GraphOptimizationLevel.
  File "/opt/miniconda3/lib/python3.7/site-packages/onnxruntime/backend/backend.py", line 80, in prepare
    return cls.prepare(bin, device, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/onnxruntime/backend/backend.py", line 69, in prepare
    inf = InferenceSession(model, options)
  File "/opt/miniconda3/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/opt/miniconda3/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: ATen is not a registered function/op

**Comment by feifeibear** [comment]
参考一下 issue #60

**Comment by feifeibear** [comment]
我弄得docker都是来自标准镜像，最新版本onnxruntime跑不起来我也无能为力，你可以按照onnxruntime官方指引配置环境进行单测。

**Comment by smartcat2010** [comment]
> 我弄得docker都是来自标准镜像，最新版本onnxruntime跑不起来我也无能为力，你可以按照onnxruntime官方指引配置环境进行单测。

谢谢！原因找到了，我之前把配置改成了安装CUDA10.2，而[ONNX官网](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md)上说其最高只支持到CUDA10.1。改成安装CUDA10.1再"pip install onnxruntime-gpu"就能把"onnxruntime"加到这个benchmark里了。
